print('      A      ')
print('     ABA     ')
print('    ABCBA    ')
print('   ABCDCBA   ')
print('  ABCDEDCBA  ')
print(' ABCDEFEDCBA ')
print('ABCDEFGFEDCBA')
print(' ABCDEFEDCBA ')
print('  ABCDEDCBA  ')
print('   ABCDCBA   ')
print('     ABA     ')
print('      A      ')